### ISSUE TITLE
Data set acquisition

### ISSUE THREAD

**Issue by liyjie** [filippos1994/Gan_mri_aug#1]
I am very interested in your experiment and want to repeat it. Could you please give me the data set used in the experiment? thank you

**Comment by djib2011** [comment]
You can download it yourself if you want to. You first need to [register an account at ADNI](https://ida.loni.usc.edu/services/NewUser.jsp?project=ADNI) and then follow the instructions we have [here](https://github.com/filippos1994/Gan_mri_aug#1-preprocessing).

**Comment by liyjie** [comment]
But I couldn't find the" MPR; GradWarp; B1 Correction; N3. Three "of the data

**Comment by liyjie** [comment]
I followed your steps to download the data, but I could not find the data you mentioned when selecting the data.such as select the "MPR; GradWarp; B1 Correction; N3; Scaled" ones

**Comment by paren8esis** [comment]
You should select "Pre-processed" in IMAGE TYPES sub-menu, instead of "Original".
We fixed the README, thanks for catching that. See if you can browse the correct images now.

**Comment by liyjie** [comment]
> You should select "Pre-processed" in IMAGE TYPES sub-menu, instead of "Original".
> We fixed the README, thanks for catching that. See if you can browse the correct images now.

Thank you
